EXECUTABLE	:= hashtable
CUFILES_sm_13 := hashtable.cu
# SMVERSIONFLAGS	:= -arch sm_11

################################################################################
# Rules and targets

include ../common_wrapper.mk

